### PR TITLE
fix flag in error message

### PR DESCRIPTION
**Pull request by vito**

### CODE REVIEW

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#116945421](https://www.pivotaltracker.com/story/show/116945421) fix flag in error message


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by goonzoid** [comment]
Since this is still used in Garden-Linux, I'm on the fence about whether it would be better to simply remove the clause about the flag. It's a little icky that this is coupled to the names of flags on whatever binary happens to use this module. Wdyt @vito @julz?

**Comment by goonzoid** [comment]
Since this is still used in Garden-Linux, I'm on the fence about whether it would be better to simply remove the clause about the flag. It's a little icky that this is coupled to the names of flags on whatever binary happens to use this module. Wdyt @vito @julz?

**Comment by goonzoid** [comment]
@vito we're gonna fix this ourselves to remove references to flags from this module, so I'll close this. Cheers though!

**Pull request closed without merging**
